---
title: "Figures Day 1"
output: html_document
date: "2025-03-23"
---

This Rmd file shows the code to produce the figures for the first day of the workshop. 

## Statistical model

```{r}
library(glmmTMB)
library(agridat)
```


```{r echo=TRUE}
data(gilmour.serpentine)
dd <- gilmour.serpentine

m1 <- glmmTMB(yield ~ 1 + gen + rep, data = dd)
m2 <- glmmTMB(yield ~ 1 + gen + (1|rep), data = dd)

m1
m2
```

```{r}
getME(m1, "X")
getME(m1, "Z")
getME(m1, "theta")

getME(m2, "X")
getME(m2, "Z")
getME(m2, "theta")
getME(m2, "b")
```


## Figures

```{r}
library(tidyverse)
library(MASS)
library(latex2exp)
```

```{r}
dd_attendees <- read.csv("../../../attendees.csv")
unique(dd_attendees$Unit.or.department.at.K.State)

dd_attendees <- dd_attendees %>% 
  mutate(dept = case_when(Unit.or.department.at.K.State %in% 
                            c("Agronomy", "Agronomy ", "Department of Agronomy") ~ "Agronomy", 
                          Unit.or.department.at.K.State %in% 
                            c("College of Veterinary Medicine/Diagnostic Medicine and Pathobiology ", 
                              "Department of Diagnostic Medicine/Pathobiology", 
                              "Diagnostic Medicine/Pathobiology ",
                              "Veterinary Medicine") ~ "Diagnostic Medicine/Pathobiology", 
                          Unit.or.department.at.K.State %in% 
                          c("Anatomy and Physiology", "Anatomy & Physiology") ~ "Anatomy & Physiology", 
                          Unit.or.department.at.K.State %in% 
                          c("ASI- Applied Swine Nutrition ", "Animal Science and Industry ", 
                            "ASI",
                            "Animals Sciences and Industry") ~ "Animal Science and Industry", 
                          Unit.or.department.at.K.State %in% 
                          c("Beef Cattle Institute, CVM") ~"Beef Cattle Institute", 
                          Unit.or.department.at.K.State %in% 
                          c("FNDH", "Department of Food, Nutrition, Health and Dietetics", 
                            "Department of Food, Nutrition, Dietetics and Health", 
                            "Food Nutrition and Health ") ~
                            "Food, Nutrition, Dietetics and Health", 
                          Unit.or.department.at.K.State %in%
                            c("KS") ~ NA,  
                          Unit.or.department.at.K.State %in%
                            c("food science") ~ "Food Science",  
                          TRUE ~ Unit.or.department.at.K.State))
unique(dd_attendees$dept)

dd_attendees %>% 
  ggplot(aes(dept))+
  geom_bar(alpha = .3, fill = "purple")+
  theme_classic()+
  theme(axis.title.x = element_blank(), 
        axis.text.x = element_text(angle = 30, hjust = .95, vjust = 1))

ggsave("../../images/day1/attendees.jpg", width = 7, height = 4)
```

```{r}
library(agridat)
data(byers.apple)
dat_apples <- byers.apple  %>% 
  mutate(day = time * 3)

dat_apples %>% 
  dplyr::select(tree, appleid) %>% 
  unique()

dat_apples %>%
  filter(appleid %in% c(1, 32, 
                        42, 88, 66, 39, 183, 250,
                        51, 77, 101, 128, 152, 208, 227), 
         between(time, 1, 5)) %>% 
  arrange(time, appleid)
dat_apples %>%
  filter(appleid %in% c(1, 32, 
                        42, 88, 66, 39, 183, 250,
                        51, 77, 101, 128, 152, 208, 227), 
         between(time, 1, 5)) %>% 
  ggplot(aes(day, diameter))+
  geom_point()+
  labs(y = "Apple diameter (cm)", x ="Day")+
  theme_classic()+
  theme(aspect.ratio = .8)

ggsave("../../images/day1/linear_regression_1.jpg", width = 7, height = 4)

```


```{r echo=FALSE, fig.width=10, message=FALSE, warning=FALSE, fig.align='center'}
set.seed(42)

x <- seq(-6, 6, length=100)
hx <- dnorm(x)
labels <- c("x ~ Normal(0, 1)", 
            "x ~ Normal(0, 16)", "x ~ Normal(2, 1)")
colors <- c("darkgreen", "tomato", "purple")


png(filename="../../images/day1/normal_univariate.png")
plot(x, dnorm(x, 0, 1), lwd=2, col= "darkgreen",
     type="l", lty= 1, xlab="x",
  ylab="[x]", main="Univariate Normal")

# lines(x, dnorm(x, 0, 1), lwd=2, col= "darkgreen")
lines(x, dnorm(x, 0, 4), lty = 2, lwd=2, col= "tomato")
lines(x, dnorm(x, 2, 1), lty = 3, lwd=2, col= "purple")

legend("topleft", inset=.05, title="Distributions",
  labels, lwd=2, lty=c(1, 2, 3), col=colors)
dev.off()
```

```{r}
set.seed(42)
dat <- mgcv::rmvn(1000, c(10, 8), matrix(c(1, .6, .6, 1), 2, 2))

png(filename="../../images/day1/normal_multivariate.jpg")
plot(dat[,1], dat[,2], xlab = TeX("$y_1$"), ylab = TeX("$y_2$"), main = "")
segments(x0 = 10, y0 = 4.5, x1 = 10, y1 = 8, col = "tomato", lwd = 3)
segments(x0 = 6.5, y0 = 8, x1 = 10, y1 = 8, col = "darkgreen", lwd = 3)
lines(sort(dat[,1]), 5 + 5*dnorm(sort(dat[,1]), 10, 1), lty = 2, lwd=3, 
      col= "tomato")
lines(7 + 2 * dnorm(sort(dat[which(dat[,2]<8),2]), 8, 1), 
      sort(dat[which(dat[,2]<8),2]),
      lty = 3, lwd=3, col= "darkgreen")
lines(7 + 2 * dnorm(sort(dat[which(dat[,2]>8),2]), 8, 1), 
      sort(dat[which(dat[,2]>8),2]),
      lty = 3, lwd=3, col= "darkgreen")
dev.off()
```

```{r}
library(agridat)
data(gilmour.serpentine)
dd <- gilmour.serpentine
dd <- dd %>% 
  mutate(rowf=factor(row), colf=factor(10*(col-8)))
str(dd)

polygon <- data.frame(rep = rep(c("R1", "R2", "R3"), each = 4), 
           col = rep(c(.5, 5.5, .5, 10.5, 10.5, 15.5), each =2), 
           row = rep(c(.5, 22.5, 22.5, .5), 3))
dd %>% 
  ggplot(aes(col, row))+
  geom_raster(aes(fill = gen), show.legend = F)+
  coord_equal()+
  geom_polygon(aes(group = rep),
               data = polygon,
               fill = NA, color = 'black')+
  rcartocolor::scale_fill_carto_d(palette = "ArmyRose",
                                  name = expression(Yield~(g~m^{-2}))) +
  theme_minimal()+
  labs(x = "Col", 
       y = "Row")

ggsave("../../images/day1/applied_example_rcbd.jpg", width = 4, height = 6)
```

